function sanitizeToken(s) {
  return s
    .replace(/::/g, "_")
    .replace(/[^A-Za-z0-9_]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/^[0-9]/, "_$&")
    .toLowerCase();
}

function extractSubsystem(text) {
  const patterns = [
    /^\[([A-Za-z][A-Za-z0-9_:./ -]{2,40})\]/,
    /^([A-Za-z][A-Za-z0-9_]+)::([A-Za-z][A-Za-z0-9_]+)/,
    /\b([A-Za-z][A-Za-z0-9_]{2,24})(?:Manager|System|Service|Controller|Network|Renderer|Inventory|Quest)\b/,
  ];
  for (const re of patterns) {
    const m = re.exec(text);
    if (!m) continue;
    if (m[2]) return `${m[1]}_${m[2]}`;
    return m[1];
  }
  return null;
}

function findContainingFunction(functions, addr) {
  for (const fn of functions) {
    if (fn.size <= 0) continue;
    if (addr >= fn.addrNum && addr < fn.addrNum + fn.size) return fn;
  }
  return null;
}

function autoNameFor(fn, token) {
  const base = sanitizeToken(token);
  if (!base) return null;
  if (/^(sub|fn)_[0-9a-f]+$/i.test(fn.name)) return `${base}_handler`;
  return null;
}

async function activate() {
  return {
    commands: [
      {
        id: "seed-names-from-strings",
        title: "Seed names from strings",
        description: "Scan log-style strings and propose function renames for anonymous handlers.",
        permissions: ["read.binary-summary", "read.strings", "read.annotations", "project.rename"],
        async run(ctx) {
          const [summary, strings, annotations] = await Promise.all([
            ctx.loadSummary(),
            ctx.loadStrings(),
            ctx.loadAnnotations(),
          ]);

          const byAddr = new Map();
          for (const fn of summary.functions) byAddr.set(fn.addr, fn);

          const proposals = [];
          const seen = new Set();
          for (const str of strings) {
            const token = extractSubsystem(str.text);
            if (!token) continue;
            for (const xref of str.xrefs) {
              const fn = findContainingFunction(summary.functions, xref);
              if (!fn) continue;
              if (annotations.renames[fn.addr]) continue;
              const proposed = autoNameFor(fn, token);
              if (!proposed) continue;
              const key = `${fn.addr}:${proposed}`;
              if (seen.has(key)) continue;
              seen.add(key);
              proposals.push(ctx.proposalBuilders.rename(fn.addr, proposed, {
                confidence: 0.72,
                reason: `log-style string "${str.text.slice(0, 72)}" is referenced inside ${fn.name}`,
              }));
            }
          }

          proposals.sort((a, b) => a.addr.localeCompare(b.addr));
          return {
            summary: proposals.length
              ? `Prepared ${proposals.length} rename proposal${proposals.length === 1 ? "" : "s"}.`
              : "No anonymous handlers matched the current string heuristics.",
            notes: "Current heuristics only rename autogenerated sub_* style functions from log or subsystem strings.",
            proposals,
          };
        },
      },
    ],
  };
}

module.exports = { activate };
