if(NOT EMBER OR NOT BINARY OR NOT WORKDIR)
    message(FATAL_ERROR "run_intel_promote.cmake: missing EMBER/BINARY/WORKDIR")
endif()

file(MAKE_DIRECTORY "${WORKDIR}")
set(_intel "${WORKDIR}/intel.jsonl")
set(_out "${WORKDIR}/promoted.ember")

file(WRITE "${_intel}"
"{\"kind\":\"claim\",\"id\":\"1\",\"agent\":\"namer\",\"ts\":\"2026-01-01T00:00:00Z\",\"subject\":\"0x401000\",\"predicate\":\"name\",\"value\":\"do_thing\",\"evidence\":\"3-arg; called by 0x402000\",\"confidence\":0.95}\n"
"{\"kind\":\"claim\",\"id\":\"2\",\"agent\":\"namer\",\"ts\":\"2026-01-02T00:00:00Z\",\"subject\":\"0x402000\",\"predicate\":\"name\",\"value\":\"low_conf_skip\",\"evidence\":\"guess\",\"confidence\":0.5}\n"
"{\"kind\":\"claim\",\"id\":\"3\",\"agent\":\"namer\",\"ts\":\"2026-01-03T00:00:00Z\",\"subject\":\"0x401010\",\"predicate\":\"note\",\"value\":\"first line\\nsecond # third\",\"evidence\":\"x\",\"confidence\":0.9}\n"
"{\"kind\":\"claim\",\"id\":\"4\",\"agent\":\"alice\",\"ts\":\"2026-01-04T00:00:00Z\",\"subject\":\"0x401020\",\"predicate\":\"name\",\"value\":\"alice_name\",\"evidence\":\"x\",\"confidence\":0.92}\n"
"{\"kind\":\"claim\",\"id\":\"5\",\"agent\":\"bob\",\"ts\":\"2026-01-05T00:00:00Z\",\"subject\":\"0x401020\",\"predicate\":\"name\",\"value\":\"bob_name\",\"evidence\":\"y\",\"confidence\":0.88}\n")

execute_process(
    COMMAND "${EMBER}" --intel-promote "${_intel}" -o "${_out}" --confidence 0.85 --quiet "${BINARY}"
    OUTPUT_VARIABLE _stdout
    ERROR_VARIABLE  _stderr
    RESULT_VARIABLE _rc
)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "ember --intel-promote failed with ${_rc}:\n${_stderr}\n--- stdout ---\n${_stdout}")
endif()

file(READ "${_out}" _actual)
string(REPLACE ";" "@SEMICOLON@" _actual_cmp "${_actual}")
string(CONCAT _expected
    "# Generated by ember-agent promote\n"
    "# Source: ${_intel}\n"
    "# Threshold: 0.85\n"
    "# 1 renames, 1 notes\n"
    "# Disputed: 1, low-conf: 1, non-promotable: 0\n"
    "\n"
    "[rename]\n"
    "0x401000 = do_thing @SEMICOLON@ conf=0.950 @SEMICOLON@ src=agent:promote @SEMICOLON@ ev=3-arg, called by 0x402000\n"
    "\n"
    "[note]\n"
    "0x401010 = first line second ♯ third @SEMICOLON@ conf=0.900 @SEMICOLON@ src=agent:promote @SEMICOLON@ ev=x\n"
    "\n")

if(NOT _actual_cmp STREQUAL _expected)
    set(_actual_path "${WORKDIR}/actual.txt")
    set(_expected_path "${WORKDIR}/expected.txt")
    file(WRITE "${_actual_path}" "${_actual}")
    file(WRITE "${_expected_path}" "${_expected}")
    execute_process(
        COMMAND diff -u "${_expected_path}" "${_actual_path}"
        OUTPUT_VARIABLE _diff
        RESULT_VARIABLE _diff_rc
    )
    message(FATAL_ERROR "intel promote output mismatch:\n${_diff}")
endif()
