import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";

import { IntelLog, intelPathFor, type Decision } from "./intel/log.js";

// Promote intel claims into a .ember script that ember --apply can ingest.
//
// Filtering rules:
//   - Skip disputed (subject, predicate) — orchestrator should resolve first.
//   - Skip below threshold (default 0.85) — uncertain claims stay agent-only.
//   - Only promote `name` and `note` predicates — they map cleanly onto
//     [rename] and [note] sections. `type` claims about new structs are
//     not promotable yet (no .ember surface for struct definitions).
//     `tag` and `xref` are agent-internal hints, not user-facing.

export interface PromoteArgs {
    binary: string;
    out: string;                 // path to write generated .ember
    threshold: number;           // default 0.85
    apply: boolean;              // run ember --apply after writing
    dryRun: boolean;             // run ember --apply --dry-run
    emberBin: string;
}

export function promote(args: PromoteArgs): {
    ember_script: string;
    promoted: number;
    skipped_disputed: number;
    skipped_low_conf: number;
    skipped_other: number;
    disputed_high_conf: string[];
} {
    const cpp = tryCppPromote(args);
    if (cpp) return cpp;

    const intel = new IntelLog(intelPathFor(args.binary));
    const view = intel.fold();

    const renames: Array<{ subject: string; value: string; conf: number; ev: string }> = [];
    const notes:   Array<{ subject: string; value: string; conf: number; ev: string }> = [];
    let disputed = 0, lowConf = 0, other = 0;
    const disputedSubjects: string[] = [];

    for (const [, d] of view) {
        if (d.disputed) {
            ++disputed;
            // Surface disputed subjects that would have promoted on
            // confidence alone — the user couldn't otherwise tell whether
            // a 0.85+ claim got skipped due to threshold or dispute.
            if (d.winner.confidence >= args.threshold) {
                disputedSubjects.push(`${d.winner.subject}|${d.winner.predicate}`);
            }
            continue;
        }
        if (d.winner.confidence < args.threshold) { ++lowConf; continue; }
        const w = d.winner;
        if (w.predicate === "name") {
            renames.push({ subject: w.subject, value: w.value, conf: w.confidence, ev: w.evidence });
        } else if (w.predicate === "note") {
            notes.push({ subject: w.subject, value: w.value, conf: w.confidence, ev: w.evidence });
        } else {
            ++other;
        }
    }

    const lines: string[] = [
        `# Generated by ember-agent promote`,
        `# Source: ${intel.path}`,
        `# Threshold: ${args.threshold}`,
        `# ${renames.length} renames, ${notes.length} notes`,
        `# Disputed: ${disputed}, low-conf: ${lowConf}, non-promotable: ${other}`,
        ``,
    ];
    if (renames.length) {
        lines.push(`[rename]`);
        for (const r of renames) {
            lines.push(`${r.subject} = ${sanitize(r.value)}${metaSuffix(r.conf, r.ev, "agent:promote")}`);
        }
        lines.push(``);
    }
    if (notes.length) {
        lines.push(`[note]`);
        for (const n of notes) {
            lines.push(`${n.subject} = ${sanitize(n.value)}${metaSuffix(n.conf, n.ev, "agent:promote")}`);
        }
        lines.push(``);
    }
    const script = lines.join("\n");

    writeFileSync(args.out, script, "utf8");

    if (args.apply || args.dryRun) {
        const cmd = ["--apply", args.out];
        if (args.dryRun) cmd.push("--dry-run");
        cmd.push(args.binary);
        const r = spawnSync(args.emberBin, cmd, { encoding: "utf8" });
        if (r.status !== 0) {
            throw new Error(`ember --apply failed: ${r.stderr || r.stdout}`);
        }
        if (args.dryRun) process.stdout.write(r.stdout);
    }

    return {
        ember_script: script,
        promoted: renames.length + notes.length,
        skipped_disputed: disputed,
        skipped_low_conf: lowConf,
        skipped_other: other,
        // Subjects that would have promoted on confidence (≥ threshold)
        // but lost to a dispute. Run a tiebreaker, then re-promote.
        disputed_high_conf: disputedSubjects,
    };
}

function tryCppPromote(args: PromoteArgs): ReturnType<typeof promote> | undefined {
    const intelPath = intelPathFor(args.binary);
    const cmd = [
        "--intel-promote", intelPath,
        "--output", args.out,
        "--confidence", String(args.threshold),
        "--json",
        "--quiet",
        args.binary,
    ];
    const r = spawnSync(args.emberBin, cmd, { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
    if (r.status !== 0) return undefined;

    let parsed: ReturnType<typeof promote>;
    try {
        parsed = JSON.parse(r.stdout) as ReturnType<typeof promote>;
    } catch {
        return undefined;
    }
    if (!parsed || typeof parsed.ember_script !== "string") return undefined;

    if (args.apply || args.dryRun) {
        const applyCmd = ["--apply", args.out];
        if (args.dryRun) applyCmd.push("--dry-run");
        applyCmd.push(args.binary);
        const apply = spawnSync(args.emberBin, applyCmd, { encoding: "utf8" });
        if (apply.status !== 0) {
            throw new Error(`ember --apply failed: ${apply.stderr || apply.stdout}`);
        }
        if (args.dryRun) process.stdout.write(apply.stdout);
    }
    return parsed;
}

// .ember directive RHS is the rest of the line up to a trailing comment;
// newlines and `#` would corrupt it. Fold both safely.
function sanitize(v: string): string {
    return v.replace(/\r?\n/g, " ").replace(/#/g, "♯");
}

function truncate(s: string, n: number): string {
    return s.length > n ? s.slice(0, n - 1) + "…" : s;
}

// Build the `; conf=… ; src=… ; ev=…` metadata suffix consumed by
// declarative.cpp's parse_meta_block. Confidence and source are
// always present; evidence is optional and tail-positioned (the
// parser slurps everything after `ev=` up to the next `;`, so we
// strip embedded `;` from evidence before emitting).
function metaSuffix(conf: number, evidence: string, source: string): string {
    const parts: string[] = [`conf=${conf.toFixed(3)}`, `src=${source}`];
    if (evidence) {
        const cleaned = evidence
            .replace(/[\r\n]+/g, " ")
            .replace(/;/g, ",")
            .trim();
        if (cleaned) parts.push(`ev=${truncate(cleaned, 200)}`);
    }
    return ` ; ${parts.join(" ; ")}`;
}
